
variable "region" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr1" {}
variable "public_subnet_cidr2" {}
variable "private_subnet_cidr1" {}
variable "private_subnet_cidr2" {}
variable "gwlb_subnet_cidr1" {}
variable "gwlb_subnet_cidr2" {}
variable "tgwattach_subnet_cidr1" {}
variable "tgwattach_subnet_cidr2" {}
variable "transit_gateway_id" {}
variable "tgw_security_route_table_id" {}
variable "tgw_spoke_route_table_id" {}
variable "gwlb_endpoint_service_name" {}
variable "gwlb_endpoint_service_type" {}
variable "tag_name_prefix" {}
variable "tag_name_unique" {}